import { GoogleAuth } from 'google-auth-library';

// Google Cloud 설정
const PROJECT_ID = process.env.GOOGLE_CLOUD_PROJECT || 'rewritemoment';
const LOCATION = 'us-central1';

// 서비스 계정 인증 정보
const credentials = process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON 
  ? JSON.parse(process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON)
  : null;

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { 
      imageUrl,       // Base64 or URL of uploaded image (사용자 셀카)
      aspectRatio = '16:9', // 16:9 (가로) or 9:16 (세로)
      movie,          // avengers, spiderman, harrypotter, lotr, starwars, jurassic
    } = req.body;

    if (!imageUrl) {
      return res.status(400).json({ error: 'Image is required' });
    }

    if (!credentials) {
      return res.status(500).json({ error: 'Google Cloud credentials not configured' });
    }

    // Google Auth 설정
    const auth = new GoogleAuth({
      credentials: credentials,
      scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // 이미지 Base64 처리 및 MIME 타입 추출
    let userImageBase64 = imageUrl;
    let mimeType = 'image/jpeg';
    
    if (imageUrl.startsWith('data:')) {
      const matches = imageUrl.match(/^data:([^;]+);base64,(.+)$/);
      if (matches) {
        mimeType = matches[1];
        userImageBase64 = matches[2];
      } else {
        userImageBase64 = imageUrl.split(',')[1];
      }
    }

    console.log('=== 2-Step Pipeline: Gemini → Veo ===');
    console.log('Movie:', movie);
    console.log('Aspect Ratio:', aspectRatio);
    console.log('User Image Base64 length:', userImageBase64?.length || 0);

    // ========================================
    // STEP 1: Gemini (나노바나나)로 셀카 이미지 생성
    // ========================================
    console.log('\n=== STEP 1: Gemini Image Generation ===');
    
    const movieInfo = getMovieInfo(movie);
    const imagePrompt = buildImagePrompt(movieInfo, aspectRatio);
    
    console.log('Image Prompt:', imagePrompt.substring(0, 200) + '...');

    // Gemini 2.0 Flash Experimental (이미지 생성 지원)
    const geminiEndpoint = `https://${LOCATION}-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/${LOCATION}/publishers/google/models/gemini-2.0-flash-exp:generateContent`;

    const geminiRequestBody = {
      contents: [{
        role: 'user',
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: userImageBase64,
            }
          },
          {
            text: imagePrompt
          }
        ]
      }],
      generationConfig: {
        responseModalities: ['TEXT', 'IMAGE'],
        temperature: 1.0,
      },
    };

    console.log('Calling Gemini API...');
    
    const geminiResponse = await fetch(geminiEndpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(geminiRequestBody),
    });

    const geminiData = await geminiResponse.json();

    if (!geminiResponse.ok) {
      console.error('Gemini API Error:', geminiData);
      return res.status(geminiResponse.status).json({ 
        error: 'Gemini image generation failed',
        details: geminiData.error?.message || JSON.stringify(geminiData)
      });
    }

    console.log('Gemini Response received');

    // Gemini 응답에서 생성된 이미지 추출
    let generatedImageBase64 = null;
    let generatedImageMimeType = 'image/png';

    if (geminiData.candidates && geminiData.candidates[0]?.content?.parts) {
      for (const part of geminiData.candidates[0].content.parts) {
        if (part.inlineData) {
          generatedImageBase64 = part.inlineData.data;
          generatedImageMimeType = part.inlineData.mimeType || 'image/png';
          console.log('Generated image found, mime:', generatedImageMimeType, 'length:', generatedImageBase64?.length);
          break;
        }
      }
    }

    // 이미지 생성 실패 시 원본 이미지 사용
    if (!generatedImageBase64) {
      console.log('No image generated by Gemini, using original image');
      generatedImageBase64 = userImageBase64;
      generatedImageMimeType = mimeType;
    }

    // ========================================
    // STEP 2: Veo로 영상 생성
    // ========================================
    console.log('\n=== STEP 2: Veo Video Generation ===');

    const videoPrompt = buildVideoPrompt(movieInfo);
    console.log('Video Prompt:', videoPrompt.substring(0, 200) + '...');

    // Veo API 엔드포인트
    const veoEndpoint = `https://${LOCATION}-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/${LOCATION}/publishers/google/models/veo-2.0-generate-001:predictLongRunning`;

    const veoRequestBody = {
      instances: [{
        prompt: videoPrompt,
        image: {
          bytesBase64Encoded: generatedImageBase64,
          mimeType: generatedImageMimeType,
        },
      }],
      parameters: {
        aspectRatio: aspectRatio,
        sampleCount: 1,
        durationSeconds: 8,
        personGeneration: 'allow_adult',
      },
    };

    console.log('Calling Veo API...');

    const veoResponse = await fetch(veoEndpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(veoRequestBody),
    });

    const veoData = await veoResponse.json();

    if (!veoResponse.ok) {
      console.error('Veo API Error:', veoData);
      return res.status(veoResponse.status).json({ 
        error: 'Veo video generation failed',
        details: veoData.error?.message || JSON.stringify(veoData)
      });
    }

    console.log('Veo Response:', JSON.stringify(veoData, null, 2));

    // Long running operation name 반환
    const operationName = veoData.name;

    return res.status(200).json({
      id: operationName,
      status: 'processing',
      message: 'Video generation started (Gemini → Veo pipeline)',
      provider: 'google-veo',
      pipeline: 'gemini-veo'
    });

  } catch (error) {
    console.error('Generation error:', error);
    return res.status(500).json({ 
      error: 'Failed to start video generation',
      details: error.message 
    });
  }
}

// 영화 정보 가져오기
function getMovieInfo(movie) {
  const movieSettings = {
    avengers: {
      title: 'Avengers',
      koreanTitle: '어벤저스',
      actors: [
        { name: 'Tony Stark / Iron Man', koreanName: '토니 스타크', look: 'Robert Downey Jr. as Tony Stark, charismatic man with goatee, wearing sleek Iron Man suit, arc reactor glowing blue on chest, confident smirk' },
        { name: 'Steve Rogers / Captain America', koreanName: '캡틴 아메리카', look: 'Chris Evans as Steve Rogers, muscular blonde man, wearing iconic Captain America uniform with star on chest, holding vibranium shield' },
        { name: 'Thor', koreanName: '토르', look: 'Chris Hemsworth as Thor, tall muscular man with long blonde hair, wearing Asgardian armor, red cape, holding Mjolnir hammer' },
        { name: 'Natasha Romanoff / Black Widow', koreanName: '블랙위도우', look: 'Scarlett Johansson as Natasha, beautiful woman with red hair, wearing black tactical suit, mysterious confident smile' },
      ],
      set: 'on the Avengers movie set, massive studio with green screens, superhero props and costumes visible, film crew and cameras in background, Marvel Studios atmosphere',
      vibe: 'exciting superhero blockbuster energy',
    },
    spiderman: {
      title: 'Spider-Man',
      koreanTitle: '스파이더맨',
      actors: [
        { name: 'Peter Parker / Spider-Man', koreanName: '피터 파커', look: 'Tom Holland as Peter Parker, young friendly man with brown hair, wearing the iconic red and blue Spider-Man suit, mask off showing his face, warm genuine smile' },
        { name: 'MJ', koreanName: 'MJ', look: 'Zendaya as MJ, young woman with curly dark hair, casual cool style, playful intelligent expression' },
        { name: 'Ned Leeds', koreanName: '네드', look: 'Jacob Batalon as Ned, friendly young man with enthusiastic excited expression' },
      ],
      set: 'on the Spider-Man movie set, New York City street backdrop, web shooting props, stunt equipment, cameras and director chairs',
      vibe: 'fun youthful friendly neighborhood hero atmosphere',
    },
    harrypotter: {
      title: 'Harry Potter',
      koreanTitle: '해리포터',
      actors: [
        { name: 'Harry Potter', koreanName: '해리 포터', look: 'Daniel Radcliffe as Harry Potter, young man with messy black hair, round glasses, lightning bolt scar on forehead, wearing Gryffindor robes, holding wand' },
        { name: 'Hermione Granger', koreanName: '헤르미온느', look: 'Emma Watson as Hermione, young woman with wavy brown hair, intelligent confident expression, wearing Gryffindor robes' },
        { name: 'Ron Weasley', koreanName: '론 위즐리', look: 'Rupert Grint as Ron, tall young man with red hair, freckles, friendly warm grin, wearing Gryffindor robes' },
      ],
      set: 'on the Harry Potter movie set at Hogwarts Great Hall, floating candles, long tables, stone walls, magical atmosphere, wizarding world decorations',
      vibe: 'magical enchanting wizarding world wonder',
    },
    lotr: {
      title: 'Lord of the Rings',
      koreanTitle: '반지의 제왕',
      actors: [
        { name: 'Frodo Baggins', koreanName: '프로도', look: 'Elijah Wood as Frodo, small man with curly brown hair and big blue eyes, wearing hobbit clothes, the One Ring on chain around neck' },
        { name: 'Gandalf', koreanName: '간달프', look: 'Ian McKellen as Gandalf, tall elderly wizard with long grey beard, wearing grey robes and pointed hat, holding wooden staff, wise knowing expression' },
        { name: 'Aragorn', koreanName: '아라곤', look: 'Viggo Mortensen as Aragorn, rugged handsome man with stubble and long dark hair, wearing ranger clothes, sword at side, noble bearing' },
        { name: 'Legolas', koreanName: '레골라스', look: 'Orlando Bloom as Legolas, ethereal blonde elf with pointed ears, wearing elvish green and brown clothes, bow and arrows on back, graceful' },
      ],
      set: 'on the Lord of the Rings movie set in New Zealand, hobbit hole props, elvish architecture, medieval weapons and armor, forest and mountains in background',
      vibe: 'epic fantasy adventure atmosphere',
    },
    starwars: {
      title: 'Star Wars',
      koreanTitle: '스타워즈',
      actors: [
        { name: 'Luke Skywalker', koreanName: '루크 스카이워커', look: 'Mark Hamill as Luke Skywalker, young man in tan Jedi robes, holding lightsaber with glowing blue blade, hopeful determined expression' },
        { name: 'Princess Leia', koreanName: '레아 공주', look: 'Carrie Fisher as Princess Leia, elegant woman with iconic side hair buns, wearing white flowing robes, regal but warm expression' },
        { name: 'Han Solo', koreanName: '한 솔로', look: 'Harrison Ford as Han Solo, roguish handsome man in white shirt and black vest, blaster at hip, cocky charming smile' },
      ],
      set: 'on the Star Wars movie set, Millennium Falcon cockpit in background, R2-D2 and C-3PO droids visible, lightsaber props, space backdrop with stars',
      vibe: 'galactic epic space opera excitement',
    },
    jurassic: {
      title: 'Jurassic Park',
      koreanTitle: '쥬라기 공원',
      actors: [
        { name: 'Dr. Alan Grant', koreanName: '그랜트 박사', look: 'Sam Neill as Dr. Alan Grant, rugged paleontologist in khaki clothes and hat, fascinated curious expression' },
        { name: 'Dr. Ellie Sattler', koreanName: '엘리 새틀러 박사', look: 'Laura Dern as Dr. Ellie Sattler, confident woman in outdoor research clothes, intelligent excited expression' },
        { name: 'Dr. Ian Malcolm', koreanName: '말콤 박사', look: 'Jeff Goldblum as Dr. Ian Malcolm, charismatic man in black leather jacket, witty knowing smirk, rock star scientist vibe' },
      ],
      set: 'on the Jurassic Park movie set, animatronic T-Rex dinosaur in background, jungle foliage, electric fences, Jurassic Park jeep, amber props',
      vibe: 'thrilling adventure mixed with wonder and danger',
    },
  };

  return movieSettings[movie] || movieSettings.avengers;
}

// STEP 1용 이미지 생성 프롬프트
function buildImagePrompt(movieInfo, aspectRatio) {
  // 랜덤하게 배우 2명 선택
  const shuffledActors = [...movieInfo.actors].sort(() => Math.random() - 0.5);
  const selectedActors = shuffledActors.slice(0, 2);

  let prompt = `[CRITICAL INSTRUCTION]
Keep the person in the uploaded image COMPLETELY UNCHANGED - their face, clothes, hair, pose, everything must stay EXACTLY as shown in the photo.

Your task: Add famous movie actors AROUND this person, as if they walked up to take a photo together.

THE PERSON IN THE UPLOADED IMAGE:
- DO NOT change their face at all
- DO NOT change their clothes or appearance  
- Keep them in the CENTER of the image
- They look happy and excited to meet the actors

ADD THESE ACTORS next to the person:
1. ${selectedActors[0].look}
2. ${selectedActors[1].look}

SCENE COMPOSITION:
- The original person is in the center, unchanged
- ${selectedActors[0].name} stands on one side, leaning in for a photo
- ${selectedActors[1].name} stands on the other side, arm around the person's shoulder
- Everyone is smiling warmly, like friends taking a group selfie
- Background: ${movieInfo.set}
- ${movieInfo.vibe}

IMPORTANT:
- This should look like a real candid photo of a fan meeting actors
- The actors look genuinely friendly and approachable
- Natural lighting from studio lights
- ${aspectRatio === '9:16' ? 'Vertical portrait format' : 'Horizontal landscape format'}
- Photorealistic quality, like an iPhone photo

Remember: The uploaded person stays EXACTLY the same, only ADD the actors around them.`;

  return prompt;
}

// STEP 2용 영상 생성 프롬프트
function buildVideoPrompt(movieInfo) {
  let prompt = `[CRITICAL] Animate this group photo into a natural, candid 8-second video.

SCENE FLOW (8 seconds):
0-2s: The group is posing for a selfie together, everyone smiling at the camera
2-4s: One actor says something funny, everyone laughs naturally
4-6s: Quick candid moment - maybe a high-five, fist bump, or the actors chatting with the fan
6-8s: The actors wave goodbye warmly, start walking back toward the film set

NATURAL INTERACTIONS:
- Actors put arms around the fan like old friends
- Genuine laughter and smiles
- Small talk gestures (nodding, pointing at camera)
- Actors act down-to-earth and friendly

CRITICAL RULES:
- The MAIN PERSON (fan) must keep their EXACT same face and clothes throughout
- Actors remain recognizable as themselves
- No morphing or distortion of any faces
- Movements are smooth and natural

STYLE:
- Behind-the-scenes vlog feel
- Warm, friendly atmosphere
- ${movieInfo.vibe}
- Camera has slight handheld movement
- Natural studio lighting

This should feel like a real fan's lucky moment meeting their favorite actors!`;

  return prompt;
}

export const config = {
  api: {
    bodyParser: {
      sizeLimit: '10mb',
    },
    responseLimit: false,
  },
};
