import { GoogleAuth } from 'google-auth-library';
import Replicate from 'replicate';

// Google Cloud 설정
const PROJECT_ID = process.env.GOOGLE_CLOUD_PROJECT || 'rewritemoment';
const LOCATION = 'us-central1';

// 서비스 계정 인증 정보
const credentials = process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON 
  ? JSON.parse(process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON)
  : null;

// Replicate 클라이언트
const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { 
      imageUrl,       // Base64 or URL of uploaded image (사용자 셀카)
      aspectRatio = '16:9',
      movie,
    } = req.body;

    if (!imageUrl) {
      return res.status(400).json({ error: 'Image is required' });
    }

    if (!credentials) {
      return res.status(500).json({ error: 'Google Cloud credentials not configured' });
    }

    console.log('=== 3-Step Pipeline: Generate → Face Swap → Veo ===');
    console.log('Movie:', movie);
    console.log('Aspect Ratio:', aspectRatio);

    // 영화 정보 가져오기
    const movieInfo = getMovieInfo(movie);

    // ========================================
    // STEP 1: Gemini로 배우들 이미지 생성 (빈 자리 포함)
    // ========================================
    console.log('\n=== STEP 1: Generate actors image with placeholder ===');

    const auth = new GoogleAuth({
      credentials: credentials,
      scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    });
    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // Gemini로 배우들 + 빈 공간(사용자 자리) 이미지 생성
    const actorsPrompt = buildActorsImagePrompt(movieInfo, aspectRatio);
    console.log('Actors Prompt:', actorsPrompt.substring(0, 200) + '...');

    const geminiEndpoint = `https://${LOCATION}-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/${LOCATION}/publishers/google/models/gemini-2.0-flash-exp:generateContent`;

    const geminiResponse = await fetch(geminiEndpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          role: 'user',
          parts: [{ text: actorsPrompt }]
        }],
        generationConfig: {
          responseModalities: ['TEXT', 'IMAGE'],
          temperature: 1.0,
        },
      }),
    });

    const geminiData = await geminiResponse.json();

    if (!geminiResponse.ok) {
      console.error('Gemini Error:', geminiData);
      return res.status(500).json({ error: 'Failed to generate actors image', details: geminiData.error?.message });
    }

    // 생성된 이미지 추출
    let actorsImageBase64 = null;
    if (geminiData.candidates?.[0]?.content?.parts) {
      for (const part of geminiData.candidates[0].content.parts) {
        if (part.inlineData) {
          actorsImageBase64 = part.inlineData.data;
          console.log('Actors image generated, length:', actorsImageBase64?.length);
          break;
        }
      }
    }

    if (!actorsImageBase64) {
      console.error('No image generated by Gemini');
      return res.status(500).json({ error: 'Failed to generate actors image - no image in response' });
    }

    // ========================================
    // STEP 2: Face Swap - 사용자 얼굴을 이미지에 합성
    // ========================================
    console.log('\n=== STEP 2: Face Swap ===');

    // 사용자 이미지 처리
    let userImageUrl = imageUrl;
    if (imageUrl.startsWith('data:')) {
      // Base64를 임시 URL로 변환 (Replicate는 URL 필요)
      userImageUrl = imageUrl;
    }

    // 배우 이미지를 data URL로 변환
    const actorsImageUrl = `data:image/png;base64,${actorsImageBase64}`;

    console.log('Running face swap...');
    console.log('User image length:', userImageUrl.length);
    console.log('Actors image length:', actorsImageUrl.length);

    // Replicate face swap 실행
    let swappedImageUrl;
    try {
      const faceSwapOutput = await replicate.run(
        "lucataco/facefusion:71e614321cf8d1ae7cba4c5f58a6e29e05130520e607f1ff5ccbcf4a2e9cb816",
        {
          input: {
            source_image: userImageUrl,  // 사용자 얼굴 (소스)
            target_image: actorsImageUrl, // 배우들 이미지 (타겟 - 여기에 얼굴 합성)
            face_enhancer: "gfpgan_1.4",
          }
        }
      );
      
      swappedImageUrl = faceSwapOutput;
      console.log('Face swap completed:', typeof swappedImageUrl);
    } catch (faceSwapError) {
      console.error('Face swap error:', faceSwapError);
      // Face swap 실패 시 원본 배우 이미지 사용
      swappedImageUrl = actorsImageUrl;
      console.log('Using original actors image (face swap failed)');
    }

    // ========================================
    // STEP 3: Veo로 영상 생성
    // ========================================
    console.log('\n=== STEP 3: Veo Video Generation ===');

    // 합성된 이미지를 Base64로 변환
    let finalImageBase64;
    let finalMimeType = 'image/png';

    if (typeof swappedImageUrl === 'string' && swappedImageUrl.startsWith('http')) {
      // URL인 경우 다운로드해서 Base64로 변환
      const imageResponse = await fetch(swappedImageUrl);
      const imageBuffer = await imageResponse.arrayBuffer();
      finalImageBase64 = Buffer.from(imageBuffer).toString('base64');
      finalMimeType = imageResponse.headers.get('content-type') || 'image/png';
    } else if (typeof swappedImageUrl === 'string' && swappedImageUrl.startsWith('data:')) {
      // Data URL인 경우
      const matches = swappedImageUrl.match(/^data:([^;]+);base64,(.+)$/);
      if (matches) {
        finalMimeType = matches[1];
        finalImageBase64 = matches[2];
      }
    } else {
      // 이미 Base64인 경우
      finalImageBase64 = actorsImageBase64;
    }

    console.log('Final image ready, length:', finalImageBase64?.length);

    // Veo 프롬프트
    const videoPrompt = buildVideoPrompt(movieInfo);
    console.log('Video Prompt:', videoPrompt.substring(0, 200) + '...');

    const veoEndpoint = `https://${LOCATION}-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/${LOCATION}/publishers/google/models/veo-2.0-generate-001:predictLongRunning`;

    const veoResponse = await fetch(veoEndpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        instances: [{
          prompt: videoPrompt,
          image: {
            bytesBase64Encoded: finalImageBase64,
            mimeType: finalMimeType,
          },
        }],
        parameters: {
          aspectRatio: aspectRatio,
          sampleCount: 1,
          durationSeconds: 8,
          personGeneration: 'allow_adult',
        },
      }),
    });

    const veoData = await veoResponse.json();

    if (!veoResponse.ok) {
      console.error('Veo Error:', veoData);
      return res.status(500).json({ error: 'Veo failed', details: veoData.error?.message });
    }

    console.log('Veo started:', veoData.name);

    return res.status(200).json({
      id: veoData.name,
      status: 'processing',
      message: 'Video generation started (3-step pipeline)',
      provider: 'google-veo',
      pipeline: 'gemini-faceswap-veo'
    });

  } catch (error) {
    console.error('Generation error:', error);
    return res.status(500).json({ 
      error: 'Failed to generate video',
      details: error.message 
    });
  }
}

// 영화 정보
function getMovieInfo(movie) {
  const movieSettings = {
    avengers: {
      title: 'Avengers',
      koreanTitle: '어벤저스',
      actors: [
        { name: 'Iron Man / Tony Stark', look: 'Robert Downey Jr. in red and gold Iron Man suit, arc reactor glowing, confident smirk, goatee beard' },
        { name: 'Captain America', look: 'Chris Evans as Captain America, muscular blonde, blue suit with star, holding shield' },
      ],
      set: 'Avengers movie set, high-tech lab background, superhero props',
      vibe: 'exciting superhero blockbuster',
    },
    spiderman: {
      title: 'Spider-Man',
      koreanTitle: '스파이더맨',
      actors: [
        { name: 'Spider-Man / Peter Parker', look: 'Tom Holland in red and blue Spider-Man suit, mask off showing face, friendly smile' },
        { name: 'MJ', look: 'Zendaya as MJ, curly dark hair, casual cool style, playful expression' },
      ],
      set: 'Spider-Man movie set, New York rooftop backdrop',
      vibe: 'fun friendly neighborhood hero vibe',
    },
    harrypotter: {
      title: 'Harry Potter',
      koreanTitle: '해리포터',
      actors: [
        { name: 'Harry Potter', look: 'Daniel Radcliffe as Harry Potter, messy black hair, round glasses, lightning scar, Gryffindor robes, wand' },
        { name: 'Hermione Granger', look: 'Emma Watson as Hermione, wavy brown hair, Gryffindor robes, intelligent expression' },
      ],
      set: 'Hogwarts Great Hall set, floating candles, magical atmosphere',
      vibe: 'magical wizarding world wonder',
    },
    lotr: {
      title: 'Lord of the Rings',
      koreanTitle: '반지의 제왕',
      actors: [
        { name: 'Gandalf', look: 'Ian McKellen as Gandalf, long grey beard, grey robes, wizard hat, wooden staff' },
        { name: 'Aragorn', look: 'Viggo Mortensen as Aragorn, rugged stubble, long dark hair, ranger clothes, sword' },
      ],
      set: 'Middle-earth movie set, Rivendell elven architecture',
      vibe: 'epic fantasy adventure',
    },
    starwars: {
      title: 'Star Wars',
      koreanTitle: '스타워즈',
      actors: [
        { name: 'Luke Skywalker', look: 'Mark Hamill as Luke, Jedi robes, blue lightsaber' },
        { name: 'Princess Leia', look: 'Carrie Fisher as Leia, iconic hair buns, white robes' },
      ],
      set: 'Star Wars set, Millennium Falcon cockpit, droids',
      vibe: 'galactic space opera',
    },
    jurassic: {
      title: 'Jurassic Park',
      koreanTitle: '쥬라기 공원',
      actors: [
        { name: 'Dr. Alan Grant', look: 'Sam Neill as Dr. Grant, khaki paleontologist clothes, hat' },
        { name: 'Dr. Ian Malcolm', look: 'Jeff Goldblum as Malcolm, black leather jacket, witty smirk' },
      ],
      set: 'Jurassic Park set, animatronic T-Rex, jungle',
      vibe: 'thrilling dinosaur adventure',
    },
  };

  return movieSettings[movie] || movieSettings.avengers;
}

// STEP 1: 배우들 + 빈 공간 이미지 생성 프롬프트
function buildActorsImagePrompt(movieInfo, aspectRatio) {
  const actors = movieInfo.actors;
  
  return `Generate a photorealistic image of a group selfie scene on a ${movieInfo.title} movie set.

THE SCENE:
- Three people taking a group selfie together, all smiling at camera
- LEFT PERSON: ${actors[0].look}
- CENTER PERSON: A generic person placeholder (will be replaced) - just show a person-shaped silhouette or average looking person in casual clothes, facing camera, smiling
- RIGHT PERSON: ${actors[1].look}
- Everyone has arms around each other in friendly pose
- Background: ${movieInfo.set}

STYLE:
- Photorealistic, like a real iPhone selfie photo
- ${movieInfo.vibe}
- Warm natural lighting
- ${aspectRatio === '9:16' ? 'Vertical portrait' : 'Horizontal landscape'} format
- All three faces clearly visible and facing camera
- Friendly candid group photo vibe

Generate a single realistic photograph.`;
}

// STEP 3: 영상 프롬프트
function buildVideoPrompt(movieInfo) {
  return `Animate this group selfie photo into a natural 8-second video.

KEEP ALL FACES EXACTLY THE SAME as in the image throughout the video.

SCENE (8 seconds):
0-2s: Everyone is posing for the selfie, holding still, smiling at camera
2-4s: Someone makes a joke, everyone laughs naturally
4-6s: Quick high-five or fist bump between the people
6-8s: The two actors on the sides wave goodbye and start walking away, the person in center waves back

STYLE:
- Natural candid behind-the-scenes feel
- ${movieInfo.vibe}
- Smooth natural movements
- Warm friendly atmosphere
- Camera has slight handheld movement

CRITICAL: Do not change, morph, or distort any faces. Keep them identical to the input image.`;
}

export const config = {
  api: {
    bodyParser: {
      sizeLimit: '10mb',
    },
    responseLimit: false,
  },
};
